FROM ollama/ollama
WORKDIR /app
COPY ollama_stuff/ollama_files/models/  /root/.ollama/models/
#COPY ["start_service.sh" , "./"]

EXPOSE 11435
#RUN chmod +x /app/start_services.sh
# Run .sh file
#CMD ["/app/start_services.sh"]"./"